name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps:
    - name: kill the existing python scripts
      run: pkill -f dungeon-bot.py
    #First we're going to checkout the repo
    - uses: actions/checkout@v2
    - name: build the directory
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
      #full path is /home/pi/Documents/discord-bot/Discord-Roguelike-main/
    - name: copy files via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: "destination/folder"
