name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    
    - name: kill the existing python scripts
      run: pkill -f dungeon-bot.py
      
    - name: Run a multi-line script
      run: |
        mkdir ../build
        cp -TR . ../build
        tar -cvf deploy.tar ../build/
        
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "deploy.tar"
        target: ${{ secrets.FILE_PATH }}
