name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps:
    - name: kill the existing python scripts
      run: pkill -f dungeon-bot.py
    #need to make the next step of figuring out how to run it
    
