name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps: 
    - name: Kill script then clone repo then run bot
      run: |
        pkill -f dungeon-bot.py
        sudo rm -r /home/pi/Discord-Roguelike
        sudo git clone https://github.com/Captain-Howard/Discord-Roguelike.git
        sudo python /home/pi/Discord-Roguelike/dungeon-bot.py &
