name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps:
    - name: kill the existing python scripts
      run: pkill -f dungeon-bot.py
    #need to make the next step of figuring out how to run it
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "start_screen_1.txt"
        target: ${{ secrets.FILE_PATH }}
