# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Display Python version
      run: python --version
  deployment:
    runs-on: self-hosted
    steps:
    - name: kill the existing python scripts
      run: pkill -f dungeon-bot.py
    - name: start the dungeon-bot 
      run: python --version
